apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Joy-it-code/my-gitops-repo.git'
    targetRevision: HEAD
    path: applications/microservice-1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
